// <auto-generated />
using Facility.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Facility.API.Migrations
{
    [DbContext(typeof(FacilityDbContext))]
    [Migration("20260501150000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .UseIdentityByDefaultColumns();

            modelBuilder.Entity("Facility.API.Models.Room", b =>
            {
                b.Property<int>("RoomId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("room_id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomId"));

                b.Property<int>("Capacity")
                    .HasColumnType("integer")
                    .HasColumnName("capacity");

                b.Property<string>("RoomName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("room_name");

                b.Property<string>("RoomStatus")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("room_status")
                    .HasDefaultValue("Active");

                b.Property<string>("RoomType")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("room_type");

                b.Property<int>("TheatreId")
                    .HasColumnType("integer")
                    .HasColumnName("theatre_id");

                b.HasKey("RoomId")
                    .HasName("PK_rooms");

                b.HasIndex("TheatreId")
                    .HasDatabaseName("IX_rooms_theatre_id");

                b.ToTable("rooms");

                b.HasData(
                    new { RoomId = 1, TheatreId = 1, RoomName = "Phòng 1", RoomType = "2D", Capacity = 120, RoomStatus = "Active" },
                    new { RoomId = 2, TheatreId = 1, RoomName = "Phòng 2", RoomType = "3D", Capacity = 100, RoomStatus = "Active" },
                    new { RoomId = 3, TheatreId = 1, RoomName = "Phòng IMAX", RoomType = "IMAX", Capacity = 200, RoomStatus = "Active" },
                    new { RoomId = 4, TheatreId = 2, RoomName = "Phòng 1", RoomType = "2D", Capacity = 150, RoomStatus = "Active" },
                    new { RoomId = 5, TheatreId = 2, RoomName = "Phòng 4DX", RoomType = "4DX", Capacity = 80, RoomStatus = "Active" },
                    new { RoomId = 6, TheatreId = 3, RoomName = "Phòng A", RoomType = "2D", Capacity = 130, RoomStatus = "Active" }
                );
            });

            modelBuilder.Entity("Facility.API.Models.Theatre", b =>
            {
                b.Property<int>("TheatreId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("theatre_id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TheatreId"));

                b.Property<string>("City")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("city");

                b.Property<string>("Coordinates")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("coordinates");

                b.Property<string>("Info")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("info");

                b.Property<string>("Location")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("location");

                b.Property<string>("PreviewUrl")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("preview_url");

                b.Property<string>("TheatreName")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("character varying(150)")
                    .HasColumnName("theatre_name");

                b.Property<string>("TheatreStatus")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("theatre_status")
                    .HasDefaultValue("Active");

                b.HasKey("TheatreId")
                    .HasName("PK_theatres");

                b.ToTable("theatres");

                b.HasData(
                    new { TheatreId = 1, TheatreName = "CGV Vincom Center", Location = "Tầng 5, Vincom Center, 72 Lê Thánh Tôn, Q.1, TP.HCM", Coordinates = "10.7769,106.7009", PreviewUrl = "", Info = "Cụm rạp cao cấp tại trung tâm Quận 1", TheatreStatus = "Active", City = "Hồ Chí Minh" },
                    new { TheatreId = 2, TheatreName = "CGV Aeon Mall Tân Phú", Location = "Tầng 3, Aeon Mall Tân Phú, 30 Bờ Bao Tân Thắng, Q.Tân Phú, TP.HCM", Coordinates = "10.8018,106.6180", PreviewUrl = "", Info = "Cụm rạp lớn tại khu vực Tân Phú", TheatreStatus = "Active", City = "Hồ Chí Minh" },
                    new { TheatreId = 3, TheatreName = "Lotte Cinema Nowzone", Location = "Tầng 5, Nowzone, 235 Nguyễn Văn Cừ, Q.1, TP.HCM", Coordinates = "10.7622,106.6882", PreviewUrl = "", Info = "Rạp chiếu phim hiện đại tại Nowzone", TheatreStatus = "Active", City = "Hồ Chí Minh" }
                );
            });

            modelBuilder.Entity("Facility.API.Models.Room", b =>
            {
                b.HasOne("Facility.API.Models.Theatre", "Theatre")
                    .WithMany("Rooms")
                    .HasForeignKey("TheatreId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Theatre");
            });

            modelBuilder.Entity("Facility.API.Models.Theatre", b =>
            {
                b.Navigation("Rooms");
            });
#pragma warning restore 612, 618
        }
    }
}
